export const permissionTable = [
    { key: "projects", label: "Projects" },
    { key: "tasks", label: "Tasks" },
    { key: "activities", label: "Activities" },
    { key: "requests", label: "Requests" },
    { key: "departments", label: "Departments" },
    { key: "users", label: "Users" },
    { key: "clients", label: "Clients" },
    { key: "roles", label: "Roles" },
    { key: "workspaces", label: "Workspaces" },
    { key: "master-schedule", label: "Master Schedule" },
    { key: "meetings", label: "Meetings" },
    { key: "contracts", label: "Contracts" },
    { key: "timesheet", label: "Timesheet" },
    { key: "invoices", label: "Invoices" },
    { key: "payments", label: "Payments" },
    { key: "reports", label: "Reports" },
    { key: "settings", label: "Settings" },
    { key: "schedule", label: "Schedule" },
    { key: "status", label: "Statuses" },
    { key: "resources", label: "Resources" },
    { key: "materials", label: "Materials" },
    { key: "equipments", label: "Equipments" },
    { key: "labors", label: "Labors" },
    { key: "resource_requests", label: "Requests Resource" },
    { key: "mywarehouse", label: "My Warehouse" },
    { key: "site-materials", label: "Site Materials" },
    { key: "site-equipments", label: "Site Equipments" },
    { key: "site-labors", label: "Site Labors" },
    { key: "priority", label: "Priorities" },
    { key: "chat", label: "Chat" },
    { key: "todos", label: "Todos" },
    { key: "sites", label: "Sites" },
    { key: "budget", label: "Budget" },
    { key: "budgets", label: "Budget Overview" },
    { key: "resource_allocation", label: "Resource Allocation" },
    { key: "warehouses", label: "Manage Warehouses" },
    { key: "transfer", label: "Transfers" },
    { key: "incoming_transfer", label: "Incoming Transfer" },
    { key: "dispatch", label: "Dispatch" },
    { key: "delivery", label: "Delivery (GRN)" },
    { key: "damages", label: "Damages & Return" },
    { key: "inventory_history", label: "Inventory History" },
    { key: "inventory_report", label: "Inventory Report" },
    { key: "hrm", label: "Hr Dashboard" },
    { key: "employee_position", label: "Job Position" },
    { key: "payslips", label: "Payslips" },
    { key: "allowances", label: "Allowances" },
    { key: "deductions", label: "Deductions" },
    { key: "expenses", label: "Expenses" },
    { key: "estimates_invoices", label: "Estimates/Invoices" },
    { key: "payment_methods", label: "Payment Methods" },
    { key: "taxes", label: "Taxes" },
    { key: "units", label: "Units" },
    { key: "items", label: "Items" },
    { key: "notes", label: "Notes" },
    { key: "leave_requests", label: "Leave Requests" },
    { key: "activity_log", label: "Activity Log" },
    { key: "general_settings", label: "General Settings" },
    { key: "permissions", label: "Permissions" },
    { key: "languages", label: "Languages" },
    { key: "email_settings", label: "E-mail" },
    { key: "sms_gateway", label: "SMS Gateway" },
    { key: "pusher", label: "Pusher" },
    { key: "media_storage", label: "Media Storage" },
    { key: "templates", label: "Templates" },
    { key: "system_updater", label: "System Updater" },
    { key: "project_report", label: "Project Report" },
    { key: "task_report", label: "Task Report" },
];